CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    quantity INT NOT NULL DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS account (
 id SERIAL PRIMARY KEY,
balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00
    );

INSERT INTO account (id, balance)
SELECT 1, 10000.00
WHERE NOT EXISTS (SELECT 1 FROM account WHERE id = 1);


